### ISSUE TITLE
CI workflows don't test macOS

### ISSUE THREAD

**Issue by ma-sadeghi** [jepegit/cellpy#279]
Currently, CI workflows run on Windows and Ubuntu, but not on macOS. Since there are two types of Mac hardware, consider adding both to your CI workflows: `macos-latest` (Intel-based), `macos-14` (Apple M chip).

**Comment by jepegit** [comment]
Need to reopen. The CI for mac using pip failed.

**Comment by jepegit** [comment]
Think it works now (replaced `pytest` with `python -m pytest` in the gitub action yml files)

**Comment by jepegit** [comment]
Works for conda and pip on macOS-14. Works for conda on macOS-latest. Not too bad. Reasonably happy with the outcome.
