### ISSUE TITLE
Example notebooks need to be updated/re-run/tested

### ISSUE THREAD

**Issue by ma-sadeghi** [jepegit/cellpy#287]
- [x] Example notebooks seem to have been updated 3-4 years ago (based on the most recent commit date). They possibly need to be updated in case the API has changed.
- [x] Also, ideally they should be uploaded in their "saved" state with the cell outputs. This is useful in case someone just wants to study them on the web (rather than clon the repo, set up a proper environment, run jupyter, etc.)
- [x] This one's optional, but highly recommended: `cellpy` seems to offer plenty of functionality, but you have very few example notebooks, which leaves users the option to comb thorugh the API, which is reasonable for most software, but probably not for research software (because the audience are mostly domain experts with far less computer expertise). I suggest you a add a few more examples to demonstrate what the software does and is capable of.
- [x] This one's optional too, but highly recommended: Despite your super comprehensive suite of unit tests, which is great, your notebooks are not tested. This is quite easy to add with huge rewards (your notebooks will never be out of sync). Here's an [example GitHub Action](https://github.com/AUTODIAL/AutoEIS/blob/develop/.github/workflows/notebooks.yml) that does so. You just need to install `nbmake` and that's pretty much it (see the Action)

**Comment by jepegit** [comment]
**Note to self**: Need to install `cellpy` in the action to be able to run notebooks using `nbmake`.
**Another note to self**: `pandas `2.2 does not handle `df.melt` as tolerant as `pandas `2.1 (multiindex columns) - need a fix for this for future versions (`pandas.stack`?)

**Comment by jepegit** [comment]
Added a few and will add more in the future.
