### ISSUE TITLE
missing data when aborting before cycle is finished

### ISSUE THREAD

**Issue by IFEStephanM** [jepegit/cellpy#60]
Arbin didnt log file when changing from cycle 2 to cycle 3. Filename: 20170519_SM_sic020_09_cc_01.res
between cycle 2 and cycle 3.

This happens because arbin did not include the last cycle in its statistics table, probably due to abort before cycle was finished. 

Maybe also add last row and check if it is included in stat-file

**Comment by jepegit** [comment]
Closing issue - will not fix this now
